### ISSUE TITLE
How to run this role? Failed with checking rails secret token.

### ISSUE THREAD

**Issue by thepenguinthatwants** [andreasscherbaum/ansible-huginn#1]
I tried running this against ubuntu 18.04

```
TASK [huginn : Check Rails Secret Token] *****************************************************************
fatal: [10.62.176.49]: FAILED! => changed=false
  msg: Change the Rails Secret Token first!

```

**Comment by andreasscherbaum** [comment]
You must change the Rails secret token, at the minimum. Otherwise your application is vulnerable.
The default is here: https://github.com/andreasscherbaum/ansible-huginn/blob/main/defaults/main.yml#L36

Don't change the default.
Copy it to vars/main.html, or set it in your inventory. Any way Ansible allows [variables to override the defaults](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) will work. Ansible gives you about 20 different ways, one is described in the README.

Please also refer to the README which explains that running this Playbook with default settings will **NOT** work, for obvious reasons: this would install a vulnerable application!
